# @package _global_
defaults:
  - /train/icassp/table2_diar_cond_styles_dset_size/base

experiment: ssp_biasing_nsf_rs_v6
data:
  use_random_segmentation: true
  train_cutsets: ${oc.env:MANIFEST_DIR}/notsofar_train_and_dev_sc_wlevel_cs.jsonl.gz
training:
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 1000
  save_steps: 1000
  eval_delay: use_amplifiers_only_n_epochs=0.015
