# @package _global_
defaults:
  - /train/icassp/table2_diar_cond_styles_dset_size/base

experiment: ssp_biasing_nsf
training:
  eval_delay: 2
data:
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/notsofar_train_sc_cutset_30s.jsonl.gz
