# @package _global_

experiment: "nsf_decode_best"

model:
  whisper_model: "openai/whisper-large-v3"
  reinit_from: "${oc.env:PRETRAINED_MODEL_PATH}"
data:
  eval_cutsets: ${oc.env:MANIFEST_DIR}/notsofar_eval_sc_cutset.jsonl.gz
training:
  decode_only: true
  eval_metrics_list: [ "tcp_wer", "cp_wer", "tcorc_wer" ]
