# @package _global_

experiment: libri2mix_decode_both

model:
  whisper_model: "openai/whisper-large-v3"
  reinit_from: "${oc.env:PRETRAINED_MODEL_PATH}"
data:
  eval_cutsets: "${oc.env:LIBRI_MIX_EVAL_PATH}" # TODO: Replace with MANIFEST_DIR
  audio_path_prefix: ${oc.env:LIBRI_AUDIO_PATH_PREFIX}
  audio_path_prefix_replacement: ${oc.env:LIBRI_AUDIO_PATH_PREFIX_REPLACEMENT}
training:
  decode_only: true
  eval_metrics_list: [ "tcp_wer", "cp_wer", "orc_wer", "tcorc_wer" ]
