# @package _global_

experiment: "ami_decode_test"

model:
  whisper_model: "openai/whisper-large-v3"
  reinit_from: "${oc.env:PRETRAINED_MODEL_PATH}"
data:
  eval_cutsets: "${oc.env:AMI_EVAL_DATA_PATH}" # TODO: Replace with MANIFEST_DIR
  audio_path_prefix: ${oc.env:AMI_AUDIO_PATH_PREFIX}
  audio_path_prefix_replacement: ${oc.env:AMI_AUDIO_PATH_PREFIX_REPLACEMENT}
training:
  decode_only: true
  eval_metrics_list: [ "tcp_wer", "cp_wer", "tcorc_wer" ]
