# @package _global_
defaults:
  - /train/cs_cont

experiment: FT_real_diar

model:
  reinit_from: /mnt/matylda5/ipoloka/projects/TS-ASR-Whisper/cs_exp/cs_from_pretrained/checkpoint-5500
  params_to_keep_frozen_keywords: null

data:
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/train/cuts_with_lang_speakers_train.jsonl.gz
  dev_cutsets:
  - ${oc.env:MANIFEST_DIR}/dev/cuts_with_lang_speakers_val.jsonl.gz
  eval_cutsets:
  - ${oc.env:MANIFEST_DIR}/test/cuts_with_lang_speakers_test_v4_real.jsonl.gz
  dataset_weights:
    - 1

training:
  decode_only: true
  eval_steps: 500
  save_steps: 500
  max_steps: 10000
  metric_for_best_model: eval_cuts_with_lang_speakers_val_tcp_wer
  bf16: false
  bf16_full_eval: false
  use_flash_attention: false
