# @package _global_
defaults:
  - /train/icassp/table5_ft-strategy/ctc_preheat_amplification/base

model:
  whisper_model: openai/whisper-large-v3-turbo
  reinit_encoder_from: ${oc.env:PRETRAINED_CTC_MODELS_PATH}/${model.whisper_model}_ctc-pretrain_libri/model.safetensors
experiment: ctc_preheat_amplification-${model.whisper_model}


training:
  learning_rate: 2e-7
  warmup_steps: 5000
  remove_timestamps_from_ctc: true

data:
  train_text_norm: "whisper"
  use_timestamps: true

