# @package _global_
defaults:
  - /train/icassp/base

wandb:
  project: icassp_table4_ssp-information
model:
  whisper_model: openai/whisper-medium.en
  reinit_encoder_from: ${oc.env:PRETRAINED_CTC_MODELS_PATH}/${model.whisper_model}_ctc-pretrain_libri/model.safetensors
  target_amp_is_diagonal: true
  target_amp_bias_only: false
  apply_target_amp_to_n_layers: 12
  target_amp_init: disparagement
data:
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/notsofar_train_sc_cutset_30s.jsonl.gz
