# @package _global_
defaults:
  - /train/icassp/table4_ssp-information/base

experiment: diag_proj_sil_non_ov
training:
  use_target_amplifiers: true
model:
  target_amp_is_diagonal: true
  target_amp_bias_only: false
  target_amp_use_silence: true
  target_amp_use_target: false
  target_amp_use_overlap: true
  target_amp_use_non_target: true
