# @package _global_
defaults:
  - /train/icassp/table4_ssp-information/base

experiment: full_proj_all_embeds
model:
  target_amp_is_diagonal: false
  target_amp_bias_only: false
  target_amp_use_silence: true
  target_amp_use_target: true
  target_amp_use_overlap: true
  target_amp_use_non_target: true
