# @package _global_
defaults:
  - /train/icassp/table1_model_comparisons/base

experiment: ssp_all_datasets
data:
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/ami-sdm_train_sc_cutset_30s.jsonl.gz
  - ${oc.env:MANIFEST_DIR}/notsofar_train_sc_cutset_30s.jsonl.gz
  - ${oc.env:MANIFEST_DIR}/libri2mix_both_100_train_sc_cutset_30s.jsonl.gz
  - ${oc.env:MANIFEST_DIR}/libri2mix_clean_100_train_sc_cutset_30s.jsonl.gz
  - ${oc.env:MANIFEST_DIR}/train-360_Libri2Mix_clean_cutset_sc.json
  - ${oc.env:MANIFEST_DIR}/train-360_Libri2Mix_both_cutset_sc.json
  dev_cutsets: ${oc.env:MANIFEST_DIR}/ami_nsf_dev_cutsets.jsonl.gz
  eval_cutsets: ${oc.env:MANIFEST_DIR}/ami_nsf_eval_cutsets.jsonl.gz
  