# @package _global_
defaults:
  - /train/icassp/table1_model_comparisons/base

experiment: ssp_all_datasets_desh_mixtures_desh_mixtures_full
training:
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 2000
  save_steps: 2000
data:
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/ami-sdm_train_sc_cutset_30s.jsonl.gz
  - ${oc.env:MANIFEST_DIR}/notsofar_train_sc_cutset_30s.jsonl.gz
  - ${oc.env:MANIFEST_DIR}/lsmix_cuts_train_clean_full_30s_max.jsonl.gz
  dev_cutsets: ${oc.env:MANIFEST_DIR}/ami_nsf_dev_cutsets.jsonl.gz
  eval_cutsets: ${oc.env:MANIFEST_DIR}/ami_nsf_eval_cutsets.jsonl.gz
