# @package _global_
defaults:
  - /train/icassp/table1_model_comparisons/base

experiment: ssp_ami_v3_fixed_lf_decoding_dgx_newcfgs_v2
data:
  train_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_train_sc_cutset_30s.jsonl.gz
  dev_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_dev_sc_cutset.jsonl.gz
  eval_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_test_sc_cutset.jsonl.gz
