# @package _global_
defaults:
  - /train/icassp/table1_model_comparisons/base

experiment: ami_turbo
model:
  whisper_model: openai/whisper-large-v3-turbo
  reinit_encoder_from: ${oc.env:PRETRAINED_CTC_MODELS_PATH}/${model.whisper_model}_ctc-pretrain_libri/model.safetensors
data:
  train_text_norm: "whisper"
  use_timestamps: true
  train_cutsets: ${oc.env:TRAIN_CUTSETS_PATH_PREFIX}/ami-sdm_cutset_train_max30s.jsonl.gz
  dev_cutsets: ${oc.env:TRAIN_CUTSETS_PATH_PREFIX}/ami-sdm_cutsets_dev_fixed_sources.jsonl.gz
  eval_cutsets: ${oc.env:TRAIN_CUTSETS_PATH_PREFIX}/ami-sdm_cutsets_test_fixed_sources.jsonl.gz
  audio_path_prefix: ${oc.env:AMI_AUDIO_PATH_PREFIX}
  audio_path_prefix_replacement: ${oc.env:AMI_AUDIO_PATH_PREFIX_REPLACEMENT}

training:
  learning_rate: 2e-7
  warmup_steps: 5000
  remove_timestamps_from_ctc: true
