# @package _global_
defaults:
  - /train/icassp/table1_model_comparisons/base

experiment: ssp_ami_decode_v3_decode
data:
  train_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_train_sc_cutset_30s.jsonl.gz
  dev_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_dev_sc_cutset.jsonl.gz
  eval_cutsets: ${oc.env:MANIFEST_DIR}/ami-sdm_test_sc_cutset.jsonl.gz
training:
  per_device_eval_batch_size: 32
  decode_only: true
  dataloader_num_workers: 4
  dataloader_prefetch_factor: 1
model:
  reinit_from: ${oc.env:PRETRAINED_MODEL_PATH}