# @package _global_
defaults:
  - /train/icassp/table1_model_comparisons/base

experiment: lsmix_turbo
model:
  whisper_model: openai/whisper-large-v3-turbo
  reinit_encoder_from: ${oc.env:PRETRAINED_CTC_MODELS_PATH}/${model.whisper_model}_ctc-pretrain_libri/model.safetensors
data:
  train_text_norm: "whisper"
  use_timestamps: true
  train_cutsets:
    - ${oc.env:LIBRI_MIX_SRC}/train-100_Libri2Mix_both_cutset_sc.json
    - ${oc.env:LIBRI_MIX_SRC}/train-100_Libri2Mix_clean_cutset_sc.json
  dev_dataset: ${oc.env:LIBRI_MIX_SRC}/dev_Libri2Mix_both_cutset_sc.json
  eval_dataset: ${oc.env:LIBRI_MIX_SRC}/test_Libri2Mix_both_cutset_sc.json
  audio_path_prefix: ${oc.env:LIBRI_AUDIO_PATH_PREFIX}
  audio_path_prefix_replacement: ${oc.env:LIBRI_AUDIO_PATH_PREFIX_REPLACEMENT}

training:
  learning_rate: 2e-7
  warmup_steps: 5000
  remove_timestamps_from_ctc: true
