# @package _global_
defaults:
  - /train/icassp/base

experiment: ${model.whisper_model}_mt_asr_spk${model.mt_num_speakers}
wandb:
  project: icassp_mt_asr
model:
  whisper_model: openai/whisper-large-v3
  reinit_encoder_from: ${oc.env:PRETRAINED_CTC_MODELS_PATH}/${model.whisper_model}_ctc-pretrain_libri/model.safetensors
  mt_asr: true
  mt_num_speakers: 4
