# @package _global_
experiment: dixtral_new_ctc_dec

wandb:
  project: dixtral_dec

model:
  dixtral_base_model: "mistralai/Voxtral-Mini-3B-2507"
  dixtral_replace_encoder_from: ${oc.env:SRC_ROOT}/dicow_large_v3
  reinit_from: "/mnt/scratch/tmp/ipoloka/tsasr/exp/dixtral_v7_replicate_7gpus_lora_w_ctc_best_replicate_proper_saving/checkpoint-3000"
  num_soft_prompts: 0
  ctc_weight: 0.3

training:
  use_lora: True
  bf16: false
  bf16_full_eval: false
  decode_only: True
  train_dixtral: True
  per_device_eval_batch_size: 4
  dataloader_num_workers: 1
  dataloader_prefetch_factor: 1
  dataloader_pin_memory: False
  remove_timestamps_from_ctc: true
  generation_max_length: 1000
  train_metrics_list: ["cp_wer"]
  eval_metrics_list: ["cp_wer"]
  predict_with_generate: true
  save_visualizations: true
  ctc_only_decoding: True

data:
  use_timestamps: false
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/notsofar1/notsofar1_sdm_eval_set_240629.1_eval_small_with_GT_cutset.jsonl.gz
  dev_cutsets:
    - ${oc.env:MANIFEST_DIR}/notsofar1/notsofar1_sdm_dev_set_240825.1_dev1_cutset.jsonl.gz
  eval_cutsets:
    - ${oc.env:MANIFEST_DIR}/notsofar1/notsofar1_sdm_eval_set_240629.1_eval_small_with_GT_cutset.jsonl.gz
  dataset_weights:
    - 1
  train_text_norm: "voxtral"
