# @package _global_
defaults:
  - /train/icassp/table2_diar_cond_styles_dset_size/base

experiment: qk_biasing_nsf_rs_v2
data:
  use_random_segmentation: true
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/notsofar_train_sc_cutset_30s.jsonl.gz
training:
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 1000
  save_steps: 1000
model:
  use_qk_biasing: true
  shift_pos_embeds: true
