# @package _global_
defaults:
  - /train/icassp/table3_ssp-ablations/base

experiment: 12_diag_disparagement
model:
  target_amp_is_diagonal: true
  target_amp_bias_only: false
  apply_target_amp_to_n_layers: 12
  target_amp_init: disparagement
