# @package _global_
defaults:
  - /train/icassp/base

wandb:
  project: icassp_table3_ssp-ablations
model:
  whisper_model: openai/whisper-medium.en
  reinit_encoder_from: ${oc.env:PRETRAINED_CTC_MODELS_PATH}/${model.whisper_model}_ctc-pretrain_libri/model.safetensors
data:
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/notsofar_train_sc_cutset_30s.jsonl.gz
