# @package _global_
defaults:
  - /train/cs_cont

experiment: joint_fixed_v3

model:
  prefixes_to_preheat: [ 'model.encoder.lang_encoder', 'model.encoder.lang_proj', 'model.encoder.fddts', 'model.encoder.initial_fddt' ]

training:
  train_with_diar: true