# @package _global_
experiment: cs_baseline

exp_dir: cs_exp

model:
  whisper_model: openai/whisper-large-v3-turbo
  reinit_encoder_from: null
  reinit_from: null
  params_to_keep_frozen_keywords:
    - "decoder"
  non_target_fddt_value: 0.25
  ctc_weight: 0

data:
  train_cutsets:
    - ${oc.env:MANIFEST_DIR}/train/xtts_cuts_with_lang_speakers_train.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/train/musc_ben_cuts_with_lang_speakers_train.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/train/musc_hin_cuts_with_lang_speakers_train.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/train/arzen_cuts_with_lang_speakers_train.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/train/seame_cuts_with_lang_speakers_train.jsonl.gz

  dev_cutsets:
    - ${oc.env:MANIFEST_DIR}/test/arzen_cuts_with_lang_speakers_test_v4.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/musc_ben_cuts_with_lang_speakers_test_v4.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/musc_hin_cuts_with_lang_speakers_test_v4.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/seame_ma_cuts_with_lang_speakers_test_v4.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/seame_sge_cuts_with_lang_speakers_test_v4.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/csfl_cuts_with_lang_speakers_test_v4_filtered.jsonl.gz
  eval_cutsets:
    - ${oc.env:MANIFEST_DIR}/test/csfl_cuts_with_lang_speakers_test_v4.jsonl.gz
  dataset_weights:
    - 1
    - 1
    - 1
    - 1
    - 1
  train_text_norm: null
  eval_text_norm: null
  use_timestamps: true

training:
  remove_timestamps_from_ctc: true
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 500
  save_steps: 500
  eval_on_start: false
  overall_batch_size: 48
  learning_rate: 2e-6
  per_device_eval_batch_size: 16
  dataloader_num_workers: 1
  dataloader_prefetch_factor: 2
  dataloader_pin_memory: true
  use_fddt_only_n_epochs: 0
  use_fddt: true
  metric_for_best_model: eval_csfl_cuts_with_lang_speakers_test_v4_filtered_cp_wer
  watch_grads: false
  max_steps: 20000
  lr_scheduler_type: cosine
  use_fddt_only_n_steps: 1000
  train_metrics_list: ["cp_wer"]
  eval_metrics_list: ["cp_wer"]
  early_stopping_patience: 4
  warmup_steps: 2000


wandb:
  project: "codeswitching_v2"
