# @package _global_
defaults:
  - /train/cs_cont

experiment: cs_whisper_ft_v2

model:
  params_to_keep_frozen_keywords: null

data:
  train_cutsets:
  - ${oc.env:MANIFEST_DIR}/train/cuts_with_lang_speakers_train_sl.jsonl.gz
  dev_cutsets:
  - ${oc.env:MANIFEST_DIR}/dev/cuts_with_lang_speakers_val_sl.jsonl.gz
  eval_cutsets:
  - ${oc.env:MANIFEST_DIR}/test/cuts_with_lang_speakers_test_v4_sl.jsonl.gz
  dataset_weights:
    - 1

training:
  metric_for_best_model: "eval_cuts_with_lang_speakers_val_sl_tcp_wer"
  use_fddt: false
  use_fddt_only_n_steps: 0
  overall_batch_size: null
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 6
