# @package _global_
defaults:
  - /train/cs_cont

experiment: cs_whisper_ft_v2_compound

model:
  params_to_keep_frozen_keywords: null
  ctc_weight: 0.0

data:
  train_cutsets:
    - ${oc.env:MANIFEST_DIR}/train/xtts_cuts_with_lang_speakers_train_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/train/musc_ben_cuts_with_lang_speakers_train_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/train/musc_hin_cuts_with_lang_speakers_train_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/train/arzen_cuts_with_lang_speakers_train_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/train/seame_cuts_with_lang_speakers_train_sl.jsonl.gz
  dev_cutsets:
    - ${oc.env:MANIFEST_DIR}/dev/xtts_cuts_with_lang_speakers_val_sl.jsonl.gz
  eval_cutsets:
    - ${oc.env:MANIFEST_DIR}/test/csfl_cuts_with_lang_speakers_test_v4_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/musc_ben_cuts_with_lang_speakers_test_v4_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/musc_hin_cuts_with_lang_speakers_test_v4_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/arzen_cuts_with_lang_speakers_test_v4_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/seame_ma_cuts_with_lang_speakers_test_v4_sl.jsonl.gz
    - ${oc.env:MANIFEST_DIR}/test/seame_sge_cuts_with_lang_speakers_test_v4_sl.jsonl.gz

training:
  metric_for_best_model: "eval_xtts_cuts_with_lang_speakers_val_sl_tcp_wer"
  use_fddt: false
  use_fddt_only_n_steps: 0
